### ISSUE TITLE
Prosba

### ISSUE THREAD

**Issue by jakubgulec** [jirkavrba/folding-stats#1]
Dobrý den,

bylo by prosím možné do statistiky uvést také tým Studentské komory Akademického senátu Fakulty stavební? Máme dokupy 450 000 bodů. Jsme samosprávním orgánem fakulty.

Předem děkuji,
s pozdravem,
Jakub Gulec - místopředseda SKAS FAST

**Comment by jirkavrba** [comment]
Určitě, přidám je na seznam sledovaných týmů.

Můžete mi prosím poslat jejich id týmu na folding?

**Comment by jakubgulec** [comment]
> Určitě, přidám je na seznam sledovaných týmů.
> 
> Můžete mi prosím poslat jejich id týmu na folding?

Jsme součástí týmu, pracujeme jako "jednotlivec" se stejným názvem na každém počítači. Nevím zda je to tedy takto možné.

Jsme v týmu 246110, naše ID je SKAS-fast

**Comment by jirkavrba** [comment]
Aha,
Pro jednotlivce tam zatím nemám podporu, ale můžu ji tam přidat, podle mě to nebude problém

**Comment by jakubgulec** [comment]
> Aha,
> Pro jednotlivce tam zatím nemám podporu, ale můžu ji tam přidat, podle mě to nebude problém

Děkujeme!

**Comment by jirkavrba** [comment]
ea0bde38d09f6fe1db4445b39ef5df9042f5b720

Přidal jsem možnost nastavit jednotlivce jako "tým". Přidal jsem SKAS-FAST jako samostatnou instituci

**Comment by jirkavrba** [comment]
Jelikož SKAS-FAST foldoval právě pod týmem, který už tam byl, zařadil jsem ho zpět pod daný tým, aby se tam nevytvořila duplicita (skóre se započítává jak pod tým folding@vut.fast, tak posléze i pod SKAS-FAST), sloučil jsem tedy do jednoho.

Viz issue https://github.com/jirkavrba/folding-stats/issues/2

**Comment by jakubgulec** [comment]
Dobrý den, rozumím, i tak děkuji za snahu.

S pozdravem,
Gulec

Stáhněte si Outlook pro Android<https://aka.ms/ghei36>

________________________________
