### ISSUE TITLE
Loading overlay not centered

### ISSUE THREAD

**Issue by antoninkriz** [jirkavrba/folding-stats#11]
![image](https://user-images.githubusercontent.com/15214494/79915888-15f29880-8428-11ea-9178-85c7cd026c45.png)

My browser:
`Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/80.0.3987.163 Chrome/80.0.3987.163 Safari/537.36`

**Comment by jirkavrba** [comment]
See issue https://github.com/jirkavrba/folding-stats/issues/4
