### ISSUE TITLE
Incorrect footer translation

### ISSUE THREAD

**Issue by antoninkriz** [jirkavrba/folding-stats#16]
`PLEASE CREATE AN ISSUE ON GITHUBU` - last word should be `GITHUB`

![image](https://user-images.githubusercontent.com/15214494/80130633-368e3000-8599-11ea-82ab-408e8c19c10f.png)

**Comment by jirkavrba** [comment]
Thanks :heart:

**Comment by jirkavrba** [comment]
Fixed
