### ISSUE TITLE
Chybějící hodnoty v grafu

### ISSUE THREAD

**Issue by pokorj54** [jirkavrba/folding-stats#19]
<img width="684" alt="cuni_graf" src="https://user-images.githubusercontent.com/43776417/80275110-86770f00-86df-11ea-9d8e-4848a208e015.PNG">
<img width="663" alt="fit_graf" src="https://user-images.githubusercontent.com/43776417/80275111-87a83c00-86df-11ea-9042-bd54e82e6593.PNG">
Občas u některých institucí chybí poslední hodnoty

**Comment by jirkavrba** [comment]
Pomůže refresh?

**Comment by pokorj54** [comment]
hmm už to zmizelo, nevím jestli pomohl refresh, nejspíš pomohlo znovu otevření stránky

**Comment by pokorj54** [comment]
Pokud bys chtěl v budoucnu reprodukovat, tak stačí mít stránku zapnutou před aktualizací grafu a navštívenou stránku s grafem nějakého týmu. A ano graf nebude aktualizovaný do dalšího refreshe nebo navštívení stránky.
