### ISSUE TITLE
Pozice SKAS FAST

### ISSUE THREAD

**Issue by MartinPilny** [jirkavrba/folding-stats#2]
Nemělo by být SKAS FAST pod VUT?

**Comment by pokorj54** [comment]
Zároveň je to jenom donor, nikoliv tým, započítává se tedy dvakrát.

**Comment by jirkavrba** [comment]
https://github.com/jirkavrba/folding-stats/issues/1

**Comment by jirkavrba** [comment]
Napadlo mě hodit k týmu folding@vut.fast exclude pro konkrétního donora, ale celé je to trochu ošemetné

**Comment by jirkavrba** [comment]
Sloučil jsem zpět do folding@vut.fast, nesedělo by to jinak se statistikou foldingu, pokud budou foldovat jako jednotlivec, oddělím to.

**Comment by jirkavrba** [comment]
Viz commit 664f3189333e69c967237e11b2f8dd7fd8b4aab5
