### ISSUE TITLE
Sjednocení formátování čísel

### ISSUE THREAD

**Issue by ostorc** [jirkavrba/folding-stats#23]
Neměli bychom sjednotit formátování čísel pro AJ verzi stránky? Teď jsou na hlavní stránce všechna čísla vždy ve formátu `xxx xxx xxx`, ale v grafech je formátování v anglické verzi `xxx,xxx,xxx`.

Když jsem dělal PR #22 tak jsem to nezkontroloval...

**Comment by ostorc** [comment]
Klidně to fixnu, ale kterou verzi podporujete?

**Comment by jirkavrba** [comment]
Podle mě je to jedno, hlavní je, že je to přehlednější
