### ISSUE TITLE
NaN pokud se nenačte tým

### ISSUE THREAD

**Issue by pokorj54** [jirkavrba/folding-stats#3]
Pokud se nenačte tým, tak se sice týmu ponechá hodnota 0, ale celkový součet je NaN. Api vrací {"error": "Not found"}

<img width="642" alt="foldingTeams" src="https://user-images.githubusercontent.com/43776417/79786466-c5a30a00-8345-11ea-8d90-7cdf2b1f7b60.PNG">
<img width="313" alt="foldingNaN" src="https://user-images.githubusercontent.com/43776417/79786468-c63ba080-8345-11ea-811e-529141685268.PNG">

**Comment by jirkavrba** [comment]
Fixed in 8d7f5727b07eb0c4adda72f118fda9b5451b53c9
