### ISSUE TITLE
Přidání NTK

### ISSUE THREAD

**Issue by ZtF** [jirkavrba/folding-stats#31]
Pokud by byl zájem, je možné zařadit i Národní technickou knihovnu, id organizace je k nalezení zde: https://stats.foldingathome.org/donor/1500543

**Comment by pokorj54** [comment]
Bohužel je NTK zařazená jako donor a nemá svůj vlastní tým. Vícero uživatelů můžou používat Folding@Home pod stejnou přezdívkou, takže by se mohly počítat body někoho jiného. Zároveň pokud by se NTK rozhodla, že se chce přidat pod nějaký tým, tak by byly body započítávány dvakrát.
