### ISSUE TITLE
Kontakty na další pracoviště z UK

### ISSUE THREAD

**Issue by hajic** [jirkavrba/folding-stats#34]
Můžete mi prosím poslat kontakty na týmy "Faculty of Science, Charles University" a "Central Library of Charles University", abych se dohodli, zda nespojit tyto statistiky pod jednu "UK"? Děkuji - email: hajic@ufal.mff.cuni.cz

**Comment by jirkavrba** [comment]
Bohužel, kontakt na ně nemám k dispozici.
Jediné, co můžu poskytnout jsou odkazy na jejich folding team přímo na stránkách projektu:
https://stats.foldingathome.org/team/258188
https://stats.foldingathome.org/team/257394

**Comment by hajic** [comment]
OK, diky. 

JH
