### ISSUE TITLE
Změna loga u FZU-LCG

### ISSUE THREAD

**Issue by madamFZU** [jirkavrba/folding-stats#36]
Dobrý den,

poprosil bych o změnu loga u teamu FZU-LCG z loga akademie na logo FZU (vizte [1], popř. [2]).

Jen pro zajímavost bych se chtěl zeptat, jak jste na náš team přišli? AFAIK jsme ho nikde nekomunikovali. Přesto jsme ale rádi, že jsme vidět na Vašem dashboardu!

Zdravím,
MAdam

[1] [FZU-S-RGB.pdf](https://github.com/jirkavrba/folding-stats/files/4661506/FZU-S-RGB.pdf)
[2] [Loga FZU](https://www.fzu.cz/loga-fyzikalniho-ustavu-akademie-ved-cr-v-v-i)

**Comment by jirkavrba** [comment]
Zařadil jsem tým pod FZU s logem ze stránek.

Na team přišel @pokorj54 ještě před tím, než vznikl tento dashboard, hledal relevatní týmy akademických institucí. Bohužel nemám více info

**Comment by pokorj54** [comment]
Daný tým jsem nalezl přes vyhledávání týmů přímo na stats.foldingathome.org.
