### ISSUE TITLE
Odstranit točícího hada

### ISSUE THREAD

**Issue by pokorj54** [jirkavrba/folding-stats#4]
Když se had točí nevidím na týmy i když už mají relevantní informaci - had může být přesunut do rohu nebo každý tým může mít hodnotu načítám

**Comment by jirkavrba** [comment]
Odebral jsem rozmazání, přesunul jsem do levého horního rohu. Místo rozmazání jsem tam přidal grayscale, jako vizuální indikaci, že probíhá načítání (v rohu už není načítání tak zřetelné)

**Comment by jirkavrba** [comment]
![image](https://user-images.githubusercontent.com/14146321/79789320-47953200-834a-11ea-87c3-6f9ce301a442.png)

**Comment by jirkavrba** [comment]
Commit 3931b5c60d5eb6a0637b9cb9150ae4b9e57bb626
