### ISSUE TITLE
Header v angličtině

### ISSUE THREAD

**Issue by vahisht** [jirkavrba/folding-stats#5]
Když už jsou názvy institucí v angličtině, šlo by udělat variantu s anglickým headerem? Mám pár přátel v research týmech v různých amerických tech companies a tohle by je mohlo zajímat! :)

**Comment by jirkavrba** [comment]
Názvy jsou podle názvů týmů přímo na folding, ale mít tam jazykové mutace je rozhodně věcná připomínka

**Comment by jirkavrba** [comment]
Added in 80038c1784833fe1ab060e73c6ea6e7fc2c0ffe5
