### ISSUE TITLE
Daily increase

### ISSUE THREAD

**Issue by Toaster192** [jirkavrba/folding-stats#6]
Pridat o kolik stouply jednotlive cisla za posledni den

Predpokladam ze s databazi by byla dost jebacka tak mozna bude stacit kazdou pulnoc stahnout html file "subscribenutych" tymu a tahat pak "historii" z nej?

**Comment by Toaster192** [comment]
Nebo bych se nedivil kdyby na neco podobneho uz neco neexistovalo

**Comment by jirkavrba** [comment]
Přidal jsem tam graf vývoje, skóre se zaznamenává každých 6 hodin
